### PR TITLE
Pipe

### PR DESCRIPTION
**Pull request by versecafe**
Add pipe operator as separator same as VSCode Rainbow CSV + simple readme

*can remove the generated files like `Package.swift` `setup.py` etc if requested*

### CODE REVIEW

**Comment by Kalmaegi** [comment]
@versecafe Thank you very much for your submission. I have some questions and need your help. I noticed that this submission contains many language formats. Can you explain to me the reason?

**Comment by versecafe** [comment]
@weartist They just got auto generated by tree sitter, I didn't really intend to make all the extras they're just kind of kicking around, I can delete whichever ones you want.

**Comment by Kalmaegi** [comment]
> @weartist They just got auto generated by tree sitter, I didn't really intend to make all the extras they're just kind of kicking around, I can delete whichever ones you want.

Yes, I guess we just need to modify the grammar.js, can you modify it to this, thank you very much :D

**Comment by versecafe** [comment]
@weartist Should have them all cleaned up

**Comment by Kalmaegi** [comment]
image
Thank you very much, I found some minor problems during testing, it seems that there are some problems with the distinction between `|`and `,` if your side is normal, I will look for the cause over the weekend

**Comment by Kalmaegi** [comment]
> @weartist Should have them all cleaned up

Sorry I'm late, I found the problem, in the grammer.js you need to deal with the pipe at the end as well. 
image

The code has been merged and I have made some minor modifications, thank you very much for your help!

**Pull request merged**
